# Generated by Django 4.1.7 on 2023-03-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_clubuser_created_at_clubuser_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubuser',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatars'),
            preserve_default=False,
        ),
    ]
