version: "3"

services:
  db:
    image: mysql:5.7
    container_name: sportify
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: sportify
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    network_mode: bridge
  redis:
    image: "redis:latest"
    container_name: "redis-sportify"
    ports:
      - "6379:6379"
