# Generated by Django 4.1.7 on 2023-03-16 21:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_members'),
        ('session', '0002_trainingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='opponent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team2_set', to='team.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_set', to='team.team'),
        ),
    ]
