# Generated by Django 4.1.7 on 2023-03-16 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='team.TeamMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
