# Generated by Django 4.1.7 on 2023-03-16 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('acquisition_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.sport')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('equipments', models.ManyToManyField(to='structure.equipment')),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='structure.venue')),
            ],
        ),
    ]
