# Generated by Django 4.1.7 on 2023-03-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Foot', 'Football'), ('Rugby', 'Rugby'), ('Basket', 'Basketball'), ('Tennis', 'Tennis')], max_length=10)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('equipments', models.ManyToManyField(to='structure.equipment')),
            ],
        ),
        migrations.RemoveField(
            model_name='venue',
            name='sport',
        ),
        migrations.DeleteModel(
            name='TrainingRoom',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
