# Generated by Django 4.1.7 on 2023-03-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_infrastructure_remove_venue_sport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.sport')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('equipments', models.ManyToManyField(to='structure.equipment')),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='structure.venue')),
            ],
        ),
    ]
